apiVersion: v1
kind: Namespace
metadata:
  name: openbao
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openbao-ns-key-manager
  namespace: openbao
  labels:
    app: openbao-ns-key-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openbao-ns-key-manager
  template:
    metadata:
      labels:
        app: openbao-ns-key-manager
    spec:
      containers:
        - name: tool
          image: ghcr.io/openkcm/openbao-tool:b0747aac0b0a4191cca07e507e4cdfd75b08a452
          env:
            - name: OPENBAO_ADDR
              value: https://openbao.openbao.svc:8200
            - name: OPENBAO_TRANSIT_PATH
              value: transit
            - name: OPENBAO_KEY_NAME
              value: example
            - name: OPENBAO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: openbao-root
                  key: root-token
            - name: OPENBAO_CA_CERT
              value: /tls/tls.crt
            - name: OPENBAO_CLIENT_CERT
              value: /admin/tls.crt
            - name: OPENBAO_CLIENT_KEY
              value: /admin/tls.key
            - name: OPENBAO_SERVER_MODE
              value: "1"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
          - mountPath: /tls
            name: tls
            readOnly: true
          - mountPath: /admin
            name: admin-client-cert
            readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
      - name: tls
        secret:
          defaultMode: 420
          secretName: openbao-tls
      - name: client-ca
        secret:
          defaultMode: 420
          secretName: openbao-client-ca-secret
      - name: admin-client-cert
        secret:
          defaultMode: 420
          secretName: openbao-admin-cert
      - emptyDir: {}
        name: home
---
apiVersion: v1
kind: Service
metadata:
  name: openbao-ns-key-manager
  namespace: openbao
spec:
  selector:
    app: openbao-ns-key-manager
  ports:
    - name: http
      port: 80
      targetPort: 8080
